### ISSUE TITLE
Chose the best k by gap statistics 

### ISSUE THREAD

**Issue by daisukekodaira** [daisukekodaira/Load-forecasting#5]
- **Is your feature request related to a problem? Please describe.**
Calculation time of "DMset_kmeans_bayesian" require much calculation time and performance is still not good. The current implementation is as follows:

`for k = 1 to 10     # investigate from k =1 to 10 `
`___for attempt = 1 to 3`
`______try "k" and check the forecasting result `
`___end `
`___calculate the average of 3 attempts`
`end`

- **Describe the solution you'd like**
Introduce gap statistics function to decide the optimal k.
You can find gap statistics function here;
[evalclusters](https://www.mathworks.com/help/stats/clustering.evaluation.gapevaluation-class.html)

- **Matlab version**
2019a

- **Additional context**
This modification seems to require much time because the original codes are in a mess.

**Comment by KiichiKato** [comment]
Kmeans_TrainingにおいてGapEvaluationを用いて自動でKの値を定められるようにしました。
